// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: source/address/city.proto

package addresspb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Division int32

const (
	Division_UNKNOWN Division = 0
	Division_EAST    Division = 1
	Division_WEST    Division = 2
	Division_NORTH   Division = 3
	Division_SOUTH   Division = 4
)

// Enum value maps for Division.
var (
	Division_name = map[int32]string{
		0: "UNKNOWN",
		1: "EAST",
		2: "WEST",
		3: "NORTH",
		4: "SOUTH",
	}
	Division_value = map[string]int32{
		"UNKNOWN": 0,
		"EAST":    1,
		"WEST":    2,
		"NORTH":   3,
		"SOUTH":   4,
	}
)

func (x Division) Enum() *Division {
	p := new(Division)
	*p = x
	return p
}

func (x Division) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Division) Descriptor() protoreflect.EnumDescriptor {
	return file_source_address_city_proto_enumTypes[0].Descriptor()
}

func (Division) Type() protoreflect.EnumType {
	return &file_source_address_city_proto_enumTypes[0]
}

func (x Division) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Division.Descriptor instead.
func (Division) EnumDescriptor() ([]byte, []int) {
	return file_source_address_city_proto_rawDescGZIP(), []int{0}
}

type City struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ZipCode string   `protobuf:"bytes,2,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Region  Division `protobuf:"varint,3,opt,name=region,proto3,enum=city.Division" json:"region,omitempty"`
}

func (x *City) Reset() {
	*x = City{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_address_city_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_source_address_city_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_source_address_city_proto_rawDescGZIP(), []int{0}
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *City) GetRegion() Division {
	if x != nil {
		return x.Region
	}
	return Division_UNKNOWN
}

var File_source_address_city_proto protoreflect.FileDescriptor

var file_source_address_city_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x2f, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x22, 0x5d, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x2a, 0x41, 0x0a, 0x08, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x41, 0x53,
	0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x45, 0x53, 0x54, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x4f, 0x55, 0x54,
	0x48, 0x10, 0x04, 0x42, 0x13, 0x5a, 0x11, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x3b, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_source_address_city_proto_rawDescOnce sync.Once
	file_source_address_city_proto_rawDescData = file_source_address_city_proto_rawDesc
)

func file_source_address_city_proto_rawDescGZIP() []byte {
	file_source_address_city_proto_rawDescOnce.Do(func() {
		file_source_address_city_proto_rawDescData = protoimpl.X.CompressGZIP(file_source_address_city_proto_rawDescData)
	})
	return file_source_address_city_proto_rawDescData
}

var file_source_address_city_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_source_address_city_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_source_address_city_proto_goTypes = []interface{}{
	(Division)(0), // 0: city.division
	(*City)(nil),  // 1: city.City
}
var file_source_address_city_proto_depIdxs = []int32{
	0, // 0: city.City.region:type_name -> city.division
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_source_address_city_proto_init() }
func file_source_address_city_proto_init() {
	if File_source_address_city_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_source_address_city_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*City); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_source_address_city_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_source_address_city_proto_goTypes,
		DependencyIndexes: file_source_address_city_proto_depIdxs,
		EnumInfos:         file_source_address_city_proto_enumTypes,
		MessageInfos:      file_source_address_city_proto_msgTypes,
	}.Build()
	File_source_address_city_proto = out.File
	file_source_address_city_proto_rawDesc = nil
	file_source_address_city_proto_goTypes = nil
	file_source_address_city_proto_depIdxs = nil
}
